version: "2.2"
services:
#  jobmanager:
#    image: flink:latest
#    ports:
#      - "8081:8081"
#    command: jobmanager
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#    volumes:
#      - "D:/data:/data"
#
#  taskmanager:
#    image: flink:latest
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    scale: 1
#    environment:
#      - |
#        FLINK_PROPERTIES=
#        jobmanager.rpc.address: jobmanager
#        taskmanager.numberOfTaskSlots: 2
#    volumes:
#      - "D:/data:/data"
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"


  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kp:
    image: applerodite/kp:latest
    environment:
      - Datasets=/data/github_package_json__with_repo_info_470698.json
      - Addr=kafka:9092
      - Topic=topic_github
      - CInterval=86400
      - PInterval=1
      - NotSleep=true
    volumes:
      - "D:/data:/data"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "D:/data:/data"